apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value:  https://github.com/neilghosh/simple-tekton-pipeline #configure: change if you want to build something else, perhaps from your own local git repository.
