apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  #name: tutorial-pipeline-run-1
  generateName: tutorial-pipeline-run-
spec:
  serviceAccountName: tutorial-service
  pipelineRef:
    name: tutorial-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: skaffold-git
    - name: web-image
      resourceRef:
        name: go-starter-service
  params:
    - name: pathToYamlFile
      value: "knative/knative-service.yaml"
    - name: imageUrl
      value: gcr.io/demoneil/tekton
    - name: imageTag
      value: "latest"
        